//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat name:.
        /// </summary>
        public static string Chat_name {
            get {
                return ResourceManager.GetString("Chat_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Chat_window_title {
            get {
                return ResourceManager.GetString("Chat_window_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client setup.
        /// </summary>
        public static string Client_setup_window {
            get {
                return ResourceManager.GetString("Client_setup_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection established.
        /// </summary>
        public static string Connection_established {
            get {
                return ResourceManager.GetString("Connection_established", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection opened. Waiting for clients..
        /// </summary>
        public static string Connection_opened_Waiting_for_clients {
            get {
                return ResourceManager.GetString("Connection_opened_Waiting_for_clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not establish a connection with the server..
        /// </summary>
        public static string Could_not_establish_a_connection_with_the_server {
            get {
                return ResourceManager.GetString("Could_not_establish_a_connection_with_the_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string Internet {
            get {
                return ResourceManager.GetString("Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local IP address.
        /// </summary>
        public static string Local_IP_address {
            get {
                return ResourceManager.GetString("Local_IP_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open connection.
        /// </summary>
        public static string Open_connection {
            get {
                return ResourceManager.GetString("Open_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Router IP address.
        /// </summary>
        public static string Router_IP_address {
            get {
                return ResourceManager.GetString("Router_IP_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server IP.
        /// </summary>
        public static string Server_IP {
            get {
                return ResourceManager.GetString("Server_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server setup.
        /// </summary>
        public static string Server_setup_window {
            get {
                return ResourceManager.GetString("Server_setup_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string TableWindow_title {
            get {
                return ResourceManager.GetString("TableWindow_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Change Background.
        /// </summary>
        public static string Window_Change_background {
            get {
                return ResourceManager.GetString("Window_Change_background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Chat.
        /// </summary>
        public static string Window_Chat {
            get {
                return ResourceManager.GetString("Window_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Client.
        /// </summary>
        public static string Window_Client {
            get {
                return ResourceManager.GetString("Window_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open _Table.
        /// </summary>
        public static string Window_Open_Table {
            get {
                return ResourceManager.GetString("Window_Open_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Server.
        /// </summary>
        public static string Window_Server {
            get {
                return ResourceManager.GetString("Window_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string Window_View {
            get {
                return ResourceManager.GetString("Window_View", resourceCulture);
            }
        }
    }
}
